# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0020_submittedpricelistrow_security_clearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='bls_data',
            fields=[
                ('series_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('series_title', models.CharField(max_length=2000)),
                ('area_code', models.CharField(max_length=100)),
                ('area_level', models.CharField(max_length=100)),
                ('area_text', models.CharField(max_length=100)),
                ('occupation_code', models.CharField(max_length=100)),
                ('occupation_text', models.CharField(max_length=300)),
                ('job_char_code', models.CharField(max_length=100)),
                ('job_char_text', models.CharField(max_length=2000)),
                ('work_level_code', models.CharField(max_length=100)),
                ('work_level_text', models.CharField(max_length=300)),
                ('average_hourly_wage', models.CharField(max_length=100)),
                ('relative_std_error', models.CharField(max_length=20)),
                ('average_hourly_wage_footnote', models.CharField(max_length=100)),
                ('relative_std_error_footnote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bls_lcat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcat_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bls_occupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_code', models.IntegerField()),
                ('occupation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='bls_occupation_lcat_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_code', models.CharField(max_length=100)),
                ('lcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_capture.bls_lcat')),
            ],
        ),
        migrations.CreateModel(
            name='bls_state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bls_state_city_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_capture.bls_state')),
            ],
        ),
    ]
