# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0021_bls_data_bls_lcat_bls_occupation_bls_occupation_lcat_mapping_bls_state_bls_state_city_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bls_occupation',
        ),
    ]
