# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0024_delete_bls_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='bls_occs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_code', models.IntegerField()),
                ('occupation', models.CharField(max_length=500)),
            ],
        ),
    ]
