# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0028_bls_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bls_pricing',
            name='area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_capture.bls_state_city_mapping'),
        ),
    ]
