# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0029_auto_20201026_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='bls_base_year_increment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_rate_inc', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
