# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0030_bls_base_year_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='bls_series_wages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.TextField()),
                ('year', models.TextField()),
                ('period', models.TextField()),
                ('value', models.TextField()),
                ('footnote_codes', models.TextField()),
                ('occupation_code', models.TextField()),
                ('lcat_id', models.TextField()),
                ('lcat_title', models.TextField()),
            ],
        ),
    ]
