# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0031_bls_series_wages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bls_series_wages',
            name='footnote_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='lcat_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='lcat_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='occupation_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='series_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bls_series_wages',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
