# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0034_bls_wage_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bls_wage_pricing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
