# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0038_auto_20201223_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='bls_series_wages_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('footnote_codes', models.TextField(blank=True, null=True)),
                ('occupation_code', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('lcat_id', models.TextField(blank=True, null=True)),
                ('lcat_title', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('commerce_industry', models.TextField(blank=True, null=True)),
                ('measure_data_type', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('period_name', models.TextField(blank=True, null=True)),
                ('latest', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bls_base_year_increment',
        ),
        migrations.DeleteModel(
            name='bls_data',
        ),
        migrations.DeleteModel(
            name='bls_occs',
        ),
        migrations.RemoveField(
            model_name='bls_occupation_lcat_mapping',
            name='lcat',
        ),
        migrations.RemoveField(
            model_name='bls_pricing',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='bls_pricing',
            name='lcat_id',
        ),
        migrations.RemoveField(
            model_name='bls_state_city_mapping',
            name='state',
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='commerce_industry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='created_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='latest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='measure_data_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='period_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bls_series_wages',
            name='updated_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='bls_lcat',
        ),
        migrations.DeleteModel(
            name='bls_occupation_lcat_mapping',
        ),
        migrations.DeleteModel(
            name='bls_pricing',
        ),
        migrations.DeleteModel(
            name='bls_state_city_mapping',
        ),
    ]
