# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0039_auto_20210114_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bls_wage_states_area_relation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_capture.bls_series_wages_a'),
        ),
    ]
